on: [push]

name: test

jobs:
  simpleExample:
    runs-on: ubuntu-18.04
    steps:
    # checkout branch
    - uses: actions/checkout@master
    - run: sleep 600
    - run: cat /etc/os-release
    - run: uname -a
    - run: uptime
    - run: cat README.md
    - run: ip addr show
    - run: cal
    - run: echo 'test'
